### ISSUE TITLE
Getting error while running the application in local

### ISSUE THREAD

**Issue by waytoharish** [aws-geospatial/amazon-location-samples-react#22]
Hi Team,

I am getting an error while running the code in local.

<img width="1598" alt="image" src="https://github.com/aws-geospatial/amazon-location-samples-react/assets/5119613/06a3c23c-0e64-4741-b9d3-0f0508b13bcd">

**Comment by vinguthh** [comment]
Hi @waytoharish 

Thanks for your feedback. To help us troubleshoot the issue quicker, could you let us know which react sample having this error?

**Comment by waytoharish** [comment]
Hi @vinguthh ,

I am trying to run map-with-amplify.

Simple steps is I just added required env variables to .env files and after npm install I am doing npm start which not loading any map for me and giving following error in browser console

**Comment by natechensan** [comment]
Hello, sorry for the delayed reply. Have you still been experiencing this issue?

I tried to reproduce the issue, but I can't seem to reproduce as of today. Here were my steps to reproduce:

1. Deployed the stack using the launch button from Readme under map-with-amplify.
2. Create an .env file in the workspace using outputs from the deployed stack.
3. `npm install`
4. `npm start`

Then I was able to see a map displayed on http://localhost:3000/. I am able to load it both on Chrome and Firefox.

<img width="1247" alt="Screenshot 2024-02-01 at 3 00 30 PM" src="https://github.com/aws-geospatial/amazon-location-samples-react/assets/2661213/dba856d3-deef-4519-8804-05bcab08d845">


My node version is 20.11.0

Output in my terminal:


  VITE v4.5.2  ready in 788 ms

  ➜  Local:   http://localhost:3000/
  ➜  Network: use --host to expose
  ➜  press h to show help

The only gap I saw was that `npm install` missing from the Readme, but according to your reply, you did run `npm install`, so I don't see a gap in your steps. Here are some steps you may try:
1. Pull the latest changes and rerun `npm install`.
2. Make sure the values in the `.env` file are correct.

If you are still experiencing the issue, can you write down the following in the comment:

1. The browser you are using.
2. Full stacks of the errors you see in the developer console.

Thank you!

**Comment by waytoharish** [comment]
its worked for me now. Thanks a lot
